USE [Company]
GO

CREATE UNIQUE CLUSTERED INDEX [ClusteredIndex-20160817-155009] ON [dbo].[Salary]
(
	[EmployeeId] ASC,
	[Month] ASC,
	[Year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


