USE [Company]
GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20160817-152307] ON [dbo].[Salary]
(
	[EmployeeId] ASC,
	[Month] ASC,
	[Year] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


